# Example scraper to demonstrate Memorious XPath narrowing
name: occrp_entity_scraper
description: A simple scrape of all the existing OCCRP investigations
# Uncomment to run this scraper automatically:
# schedule: weekly
pipeline:
  init:
    # Start URL
    method: seed
    params:
      urls:
        - https://www.occrp.org/en/investigations
    handle:
      pass: fetch
  fetch:
    # Download the page passed from the seed stage.
    method: fetch
    params:
      rules:
        and:
          - pattern: '.*investigations.*'
          - domain: occrp.org
          - not:
              or:
                - domain: vis.occrp.org
                - domain: tech.occrp.org
                - domain: data.occrp.org
                - mime_group: assets
                - mime_group: images
                - pattern: "https://www.occrp.org/en/component/.*"
                - pattern: "https://www.occrp.org/en/donate.*"
                - pattern: "https://www.occrp.org/.*start=.*"
                - pattern: "https://www.occrp.org/ru/.*"
    handle:
      pass: parse
  parse:
    method: example.article:parse
    params:
      schema: Article
      store:
        and:
          - mime_group: web
      properties:
        title: .//meta[@property="og:title"]/@content
        author: .//meta[@name="author"]/@content
        publishedAt: .//*[@class="date"]/text()
        description: .//meta[@property="og:description"]/@content
    handle:
      store: store
      fetch: fetch
  store:
    # Store the crawled document as an ftm entity
    method: aleph_emit_entity